server:
  port: 9000
logging:
  config: classpath:log4j2-spring.xml

spring:
  profiles:
    include: key
  servlet:
    multipart:
      # big-file-upload
      max-file-size: 1024MB
      max-request-size: 1024MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/z-spring?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 191002


# diy
make-html-domain: "http://192.168.68.57:9000/index?htmlStr="


